apiVersion: v1
kind: Service
metadata:
  name: analytics-api
spec:
  type: LoadBalancer     # Or NodePort, depending on cluster
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: analytics-api
