apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  RAW_DB_HOST: pgsqldb.maavee.net1
  RAW_DB_PORT: "5432"
  RAW_DB_NAME: "smail_raw"
  ANALYTICS_DB_HOST: pgsqldb.maavee.net1
  ANALYTICS_DB_PORT: "5432"
  ANALYTICS_DB_NAME: "smail_analytics"
  AGG_INTERVAL_MINUTES: "10"
  AGG_INTERVAL_SECONDS: "600"
  API_PORT: "3000"
  LLM_MODEL: "gpt-4o-mini"
