apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:
  RAW_DB_USER: postgres
  RAW_DB_PASS: cG9zdG8yZXM
  ANALYTICS_DB_USER: postgres
  ANALYTICS_DB_PASS: cG9z8GdyZXM
  LLM_API_KEY: sk-proj-0078j46k
