apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
stringData:
  RAW_DB_USER: smail_user
  RAW_DB_PASS: "smail123"
  ANALYTICS_DB_USER: smail_user
  ANALYTICS_DB_PASS: "smail123"
  LLM_API_KEY: sk-proj-0078j46k
