apiVersion: apps/v1
kind: Deployment
metadata:
  name: primary-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primary-db
  template:
    metadata:
      labels:
        app: primary-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          envFrom:
            - secretRef:
                name: database-secrets
          env:

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: analytics-db-secret
                  key: RAW_DB_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: analytics-db-secret
                  key: RAW_DB_PASS

            - name: POSTGRES_DB
              value: metricsdb

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: primary-data
      volumes:
        - name: primary-data
          persistentVolumeClaim:
            claimName: primary-db-pvc
  initContainers:
    - name: init-raw-db
      image: postgres:16
      command:
        - sh
        - -c
        - |
          psql -v ON_ERROR_STOP=1 \
              -h primary-db \
              -U postgres \
              -d metricsdb \
              -f /schema/raw_schema.sql
      volumeMounts:
        - name: db-schema
          mountPath: /schema
